[project]
name = "ask-oogway"
version = "0.1.0"
description = "Simple CLI tool for saving tokens by using expensive models only for hard questions/decisions."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
ask-oogway = "ask_oogway:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
